import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Box,
  Card,
  CardContent,
  Chip,
  Divider,
  Grid,
  Typography,
} from "@mui/material";

import CityMap from "../../components/map/CityMap";
import SimulateButton from "../../components/recommendations/SimulateButton";
import SimulationImpact from "../../components/recommendations/SimulationImpact";
import SimulationStatus from "../../components/recommendations/SimulationStatus";
import { useSimulation } from "../../context/SimulationContext";
import { getRecommendations } from "../../services/recommendationService";
import type { SensorRecommendation } from "../../services/recommendationEngine";
import { explainRecommendation } from "../../utils/explainRecommendation";

export default function Recommendations() {
  const [recommendations, setRecommendations] = useState<
    SensorRecommendation[]
  >([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  const { simulatedStations } = useSimulation();

  useEffect(() => {
    async function loadRecommendations() {
      try {
        const data = await getRecommendations(simulatedStations);
        setRecommendations(data);
      } catch {
        setError("Could not load backend recommendations.");
      } finally {
        setLoading(false);
      }
    }

    loadRecommendations();
  }, [simulatedStations]);

  const visibleRecommendations = useMemo(
    () =>
      recommendations.filter(
        (candidate) =>
          !simulatedStations.some(
            (station) =>
              station.lat === candidate.lat &&
              station.lng === candidate.lng,
          ),
      ),
    [recommendations, simulatedStations],
  );

  return (
    <Box>
      <Typography variant="h4" sx={{ fontWeight: 700 }}>
        AI Sensor Recommendations
      </Typography>

      <Typography color="text.secondary" sx={{ mt: 1, mb: 3 }}>
        Recommendations are generated by the FastAPI backend using monitoring
        coverage, estimated PM2.5 and wind-dispersion risk.
      </Typography>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      <SimulationStatus />

      <SimulationImpact />

      <Box sx={{ mb: 4 }}>
        <CityMap />
      </Box>

      <Typography
        variant="h5"
        sx={{
          fontWeight: 700,
          mb: 2,
        }}
      >
        Top Recommended Locations
      </Typography>

      {loading && (
        <Typography color="text.secondary">
          Loading backend recommendations...
        </Typography>
      )}

      {!loading && visibleRecommendations.length === 0 && (
        <Alert severity="info">
          No remaining recommendations are available.
        </Alert>
      )}

      <Grid container spacing={3}>
        {visibleRecommendations.map((candidate, index) => {
          const explanation = explainRecommendation(candidate);

          return (
            <Grid
              key={candidate.id}
              size={{ xs: 12, md: 6, lg: 4 }}
            >
              <Card
                variant="outlined"
                sx={{
                  height: "100%",
                  borderRadius: 3,
                }}
              >
                <CardContent>
                  <Box
                    sx={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      gap: 2,
                      mb: 2,
                    }}
                  >
                    <Typography
                      variant="h6"
                      sx={{ fontWeight: 700 }}
                    >
                      {`Recommendation #${index + 1}`}
                    </Typography>

                    <Chip
                      label={`Score ${candidate.priorityScore}`}
                      color={index === 0 ? "error" : "primary"}
                    />
                  </Box>

                  <Typography>
                    <strong>Coverage gap:</strong>{" "}
                    {candidate.coverageScore}/100
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Estimated PM2.5:</strong>{" "}
                    {candidate.estimatedPm25.toFixed(2)} µg/m³
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>PM2.5 risk:</strong>{" "}
                    {candidate.pm25Risk.toFixed(0)}/100
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Estimated wind speed:</strong>{" "}
                    {candidate.estimatedWindSpeed.toFixed(2)} m/s
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Low-wind risk:</strong>{" "}
                    {candidate.windRisk.toFixed(0)}/100
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Nearest station:</strong>{" "}
                    {candidate.nearestStation}
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Distance:</strong>{" "}
                    {candidate.distanceKm.toFixed(2)} km
                  </Typography>

                  <Typography sx={{ mt: 1 }}>
                    <strong>Coordinates:</strong>{" "}
                    {candidate.lat.toFixed(5)},{" "}
                    {candidate.lng.toFixed(5)}
                  </Typography>

                  <Divider sx={{ my: 2 }} />

                  <Typography
                    variant="subtitle2"
                    sx={{ fontWeight: 700, mb: 1 }}
                  >
                    {explanation.title}
                  </Typography>

                  {explanation.reasons.map((reason) => (
                    <Typography
                      key={reason}
                      variant="body2"
                      color="text.secondary"
                      sx={{ mb: 0.75 }}
                    >
                      • {reason}
                    </Typography>
                  ))}

                  <Box
                    sx={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      gap: 1,
                      mt: 2,
                    }}
                  >
                    <Chip
                      color="success"
                      label={`Confidence ${explanation.confidence}%`}
                    />

                    <Typography
                      variant="caption"
                      color="text.secondary"
                    >
                      Backend Decision Support
                    </Typography>
                  </Box>

                  <SimulateButton recommendation={candidate} />
                </CardContent>
              </Card>
            </Grid>
          );
        })}
      </Grid>
    </Box>
  );
}